name: Update CPAN module manually.

env:
  perl-version: "5.40"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      module:
        description: The updating module name.
        type: string
        required: true

jobs:
  bump-cpanfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/composite/update-cpan-module
        with:
          perl-version: ${{ inputs.perl-version }}
          module: ${{ inputs.module }}
