name: Update CPAN module manually.

env:
  perl-version: "5.40"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      module:
        description: The updating module name.
        type: string
        required: true

jobs:
  bump-cpanfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/composite/update-cpan-module
        with:
          perl-version: ${{ inputs.perl-version }}
          module: ${{ inputs.module }}
