name: Update CPAN module manually.

env:
  perl-version: "5.40"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      module:
        description: The updating module name.
        type: string
        required: true

jobs:
  bump-cpanfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/composite/update-cpan-module
        with:
          perl-version: ${{ inputs.perl-version }}
          module: ${{ inputs.module }}
