name: Automatic update to nix flake.lock

on:
  schedule:
    - cron: "45 16 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update nix flake
        run: nix flake update

      - name: Make metadata
        id: meta
        run: |
          {
            echo "date=$(date +%Y-%m-%d)"
          } >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          title: "chore(flake): update nix flake at ${{ steps.meta.outputs.date }}"
          commit-message: "chore(flake): update nix flake at ${{ steps.meta.outputs.date }}"
          branch: "update-nix-flake-at-${{ steps.meta.outputs.date }}"
          add-paths: |
            flake.lock
