name: Run tests for p5-Kalaclista

env:
  perl-version: '5.40'

on:
  pull_request:
    branches: ["*"]
    paths:
      - ".github/workflows/test-p5-Kalaclista.yml"
      - "cpanfile"
      - "cpanfile.snapshot"
      - "lib/**"
      - "t/**"
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install XS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            --assume-yes \
            --no-install-recommends \
            libidn-dev
      - uses: shogo82148/actions-setup-perl@f9f0bf89e0d19ddbabb2f40d43db2e944bce7d2f # v1.36.0
        with:
          perl-version: ${{ env.perl-version }}
      - name: Install CPAN module dependencies
        run: |
          cpm install -Llocal Carton::Snapshot
          cpm install -Llocal
      - name: Run tests
        run: |
          prove -Ilocal/lib/perl5 -Ilib -It/lib -vr t/
